# Generated by Django 5.2 on 2025-05-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_tipovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fabricante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.fabricante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.tipovehiculo'),
            preserve_default=False,
        ),
    ]
