# Generated by Django 5.2 on 2025-05-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_post_fabricante_post_tipo_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tipo_vehiculo',
        ),
    ]
