# Generated by Django 5.2.1 on 2025-05-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_remove_post_fabricante_remove_post_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion.fabricante'),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion.tipovehiculo'),
        ),
    ]
