# Generated by Django 5.2 on 2025-06-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_post_fabricante_post_tipo_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('cilindrada', models.CharField(max_length=100)),
                ('transmision', models.CharField(max_length=100)),
                ('velocidades', models.PositiveIntegerField()),
                ('combustible', models.CharField(max_length=100)),
                ('rendimiento_ciudad', models.CharField(max_length=100)),
                ('rendimiento_carretera', models.CharField(max_length=100)),
                ('rendimiento_mixto', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('puertas', models.PositiveIntegerField()),
                ('asientos', models.PositiveIntegerField()),
                ('llantas', models.CharField(max_length=100)),
                ('llantas_tamano', models.CharField(max_length=100)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='Aplicacion.post')),
            ],
        ),
    ]
