# Generated by Django 5.2 on 2025-06-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_detallevehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallevehiculo',
            name='ciudad',
        ),
    ]
